### ISSUE TITLE
Identifier "u32_t" is undefined

### ISSUE THREAD

**Issue by lnsriravichandran22** [doragasu/esp8266-rtos-sntp#1]
Hi Doragasu,

I am getting this Error on the definition inside the function "static void sntp_process".

Please refer the screen shot
![ntohl error](https://cloud.githubusercontent.com/assets/7059339/14198275/c8f1a4e4-f7f5-11e5-9037-e3bea608e3e5.png)

**Comment by doragasu** [comment]
Most likely there is a problem with your include files. Can you build sntp example under `examples/sntp`?

If it builds, try using all the include files in the example, in the same order.

**Comment by lnsriravichandran22** [comment]
Sorry for asking this. Could you please share the working project set of sntp project? Also let me know , which IDE are you using.

**Comment by doragasu** [comment]
I didn't notice you are testing this old repo. I'm trying to merge my sntp implementation into esp-open-rtos, see [PR #114](https://github.com/SuperHouse/esp-open-rtos/pull/114). Until this gets merged, it's better if you use [the branch sntp of my fork of their repo](https://github.com/doragasu/esp-open-rtos/tree/sntp).

**Comment by lnsriravichandran22** [comment]
Thank you So Much!! 

Could you please help me with this?

![output](https://cloud.githubusercontent.com/assets/7059339/14200499/f0723a48-f808-11e5-987d-ecf4e3a46175.png)

**Comment by doragasu** [comment]
Did you add `EXTRA_COMPONENTS = extras/sntp` to the Makefile?
